#!/bin/bash
#
# Script to update the Arduino Yun packages via ssh
#
# * Requires sshpass package (sudo apt-get install sshpass)
#
# Created: 
#   David Fdez (davidfr@hopu.eu)
#

echo

if ! type sshpass > /dev/null; then
  echo "sshpass command is required to run this script. You can use <sudo apt-get install sshpass> to install it. Abort"
  exit 1
fi

# Requesting target ip
echo -n "Target IP [192.168.240.1]: "
read targetip

# If no target ip specified, then default is arduino.local (192.168.240.1)
if [ -z $targetip ] 
then
  targetip=192.168.240.1
fi

if [ "$targetip" != "192.168.240.1" ] 
then
	# Check if IPv4 is correct formatted
	if expr "$targetip" : '[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$' >/dev/null; then
	  IFS=.
	  set $targetip
	  for quad in 1 2 3 4; do
	    if eval [ \$$quad -gt 255 ]; then
	      echo "Specified IPv4 does not have the correct format."
	      exit 1
	    fi
	  done
	else
	  echo "Specified IPv4 does not have the correct format."
	  exit 1
	fi
fi

# Requesting user
echo -n "User [root]: "
read user
echo 

# If no user specified, then default is root
if [ -z $user ] 
then
  user=root
fi

# Requesting password to user
echo -n "Root password: "
read -s pass
echo

# Check password specified
if [ -z $pass ] 
then
  echo "No password provided."
  exit 1
else 
  # Store as environment variable
  export SSHPASS=$pass
fi
echo

echo "Updating packages in device..."
sshpass -e ssh -o StrictHostKeyChecking=no -l "$user" "$targetip" "opkg update"

echo "Done."

# Remove environment variable
unset SSHPASS
